name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ GITHUB_TOKEN_KEY }}
          USERNAME: ${{ GIT_USERNAME }}
      - name: Commit & Push
        run: |
          git config user.name aminenurgynk
          git config user.email amine.gynk@gmail.com
          git add -A .
          git commit -m "generated"
          git push
